import { NextRequest, NextResponse } from 'next/server';
import { buildSummaryPrompt, validateAzureConfig, generateDummySummary } from '@/lib/aiSummary';
import type { AISummaryRequest, AISummaryResponse } from '@/lib/types';

/**
 * POST /api/ai-summary
 *
 * Generates an AI-powered executive summary of retirement plan fee benchmarking data
 * using Azure OpenAI.
 *
 * Request body: AISummaryRequest
 * Response: AISummaryResponse (streaming or JSON)
 */
export async function POST(request: NextRequest) {
  try {
    // Parse request body
    const summaryRequest: AISummaryRequest = await request.json();

    // Validate Azure OpenAI configuration
    const configValidation = validateAzureConfig();
    if (!configValidation.valid) {
      // Return dummy data for development/demo purposes
      console.log('Azure OpenAI not configured, returning dummy summary');
      const dummySummary = generateDummySummary(summaryRequest);
      return NextResponse.json({
        summary: dummySummary,
      } as AISummaryResponse);
    }

    // Build the prompt
    const prompt = buildSummaryPrompt(summaryRequest);

    // Call Azure OpenAI API
    const endpoint = process.env.AZURE_OPENAI_ENDPOINT!;
    const apiKey = process.env.AZURE_OPENAI_API_KEY!;
    const deployment = process.env.AZURE_OPENAI_DEPLOYMENT!;
    const apiVersion = process.env.AZURE_OPENAI_API_VERSION || '2024-02-15-preview';

    const url = `${endpoint}/openai/deployments/${deployment}/chat/completions?api-version=${apiVersion}`;

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'api-key': apiKey,
      },
      body: JSON.stringify({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        max_tokens: 1000,
        temperature: 0.7,
        top_p: 0.95,
        frequency_penalty: 0,
        presence_penalty: 0,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Azure OpenAI API error:', errorText);
      return NextResponse.json(
        {
          error: `Azure OpenAI API error: ${response.status} ${response.statusText}`,
          summary: '',
        } as AISummaryResponse,
        { status: response.status }
      );
    }

    const data = await response.json();

    // Extract the generated summary
    const summary = data.choices?.[0]?.message?.content || '';

    if (!summary) {
      return NextResponse.json(
        {
          error: 'No summary generated by AI',
          summary: '',
        } as AISummaryResponse,
        { status: 500 }
      );
    }

    return NextResponse.json({
      summary,
    } as AISummaryResponse);
  } catch (error) {
    console.error('Error generating AI summary:', error);
    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : 'Unknown error occurred',
        summary: '',
      } as AISummaryResponse,
      { status: 500 }
    );
  }
}

/**
 * GET handler returns method not allowed
 */
export async function GET() {
  return NextResponse.json(
    { error: 'Method not allowed. Use POST to generate summaries.' },
    { status: 405 }
  );
}
